### ISSUE TITLE
コミットでerrorが出るものの、Build時はerrorが0

### ISSUE THREAD

**Issue by w-tensyo** [w-tensyo/ScaleGenerator#1]
Githubにコミットするタイミングではerror 1　と出るものの、Build時はerrorが0になります。
どういうことでしょうか・・・？

**Comment by shinsuke-fujita** [comment]
これって具体的にどこのソースコードがerrorになってるとか分かりますかね？

**Comment by w-tensyo** [comment]
ごめんなさい・・・エンハンスで色々いじっていたらもう出なくなりました・・・w
その代わり別の問題が・・・。

0errorと出ているものの、アプリを起動するとクラッシュします。
1st_implementation_enhのブランチにコミットしているのですが・・・
Stringをソートして、それをList<String>で配列化。それをグローバル変数"toneList"に格納して、adapterで利用する。といった想定で記入しています。

何が悪いのか、よければレビューしていただけますと幸いです！
（P.S. うまくできていないものの、なんだか「こう使えばいいのでは？」というのがイメージだけはできるようになってきました！）

**Comment by shinsuke-fujita** [comment]
起動直後のエラー原因ですが、以下です。
MainActivity.java line27
`TextView dispSortTone = (TextView) findViewById(R.id.sort_tone_string);TextView dispSortTone = (TextView) findViewById(R.id.sort_tone_string);`

これはレイアウトファイルからViewを取得する処理ですが、インスタンス変数の宣言領域に書いてます。
findViewById()メソッドはonCreate()メソッドでsetContentView(R.layout.activity_main);した後に記述しないといけないのでNullPointerExceptionが発生してました。

Logcatにエラーが出力されていましたので、そちらも見るように習慣付けましょう。

**Comment by shinsuke-fujita** [comment]
細かい処理は後ほど見れたら見ます。

**Comment by w-tensyo** [comment]
ありがとうございます！
変数の宣言と、変数の代入？の処理を分けました。
グローバル変数として宣言（そのまま）
指摘いただいた通り、onCreate()メソッド内でfindViewByIdを記述しました。

が、引き続き以下のエラーが出ています。
おそらく、配列の処理がうまくいっていない→Adapterの第3引数でnullが発生して落ちている。といった感じなのでは？と推測しています・・・。

エラーコード
`2019-10-13 13:26:34.541 14684-14684/com.example.wtensyo.scalegenerator E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.wtensyo.scalegenerator, PID: 14684
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.wtensyo.scalegenerator/com.example.wtensyo.scalegenerator.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
        at android.widget.ArrayAdapter.getCount(ArrayAdapter.java:380)
        at android.widget.ListView.setAdapter(ListView.java:575)
        at com.example.wtensyo.scalegenerator.MainActivity.onCreate(MainActivity.java:46)
        at android.app.Activity.performCreate(Activity.java:7009)
        at android.app.Activity.performCreate(Activity.java:7000)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) `

独自ソートした後に配列化させようとしているメソッド
`    //sortToneUtilで切り出した文字列をList<String>で配列化させる処理
    static List<String> makeArray(String a){
        List<String> toneMake = Arrays.asList(a.split(","));
        return toneMake;
    }`

**Comment by shinsuke-fujita** [comment]
今更ですいません。
このログだと `NullPointerException`がMainActivity.javaの46行目で発生してますね。
リストのサイズを参照しようとしてるけどリスト自体がnullみたいですね。

**Comment by shinsuke-fujita** [comment]
クラッシュしてる真の理由が分かりました。

> おそらく、配列の処理がうまくいっていない→Adapterの第3引数でnullが発生して落ちている。といった感じなのでは？と推測しています・・・。

この推測は合ってます！
toneListがインスタンス変数で定義されてますが、初期化をしてないためまずはtoneListはnullの状態です。
toneListはleftSpinnerが選択された時に値が入るため起動時にはnullのままadapterを初期化しようとしてクラッシュしてるようです。（adaperの内部処理でlist.size()にアクセスしてるためlistがnullだとNG）
そのため回避方法はインスタンス変数を宣言する時に初期化も同時に行うようにするですね。
NG：`List<String> toneList;`
OK：`List<String> toneList = new ArrayList<>();`

**Comment by shinsuke-fujita** [comment]
配列処理の所感
* sortToneUtilメソッドとmakeArrayメソッドはわざわざメソッド化しなくてもいいかも。
* メソッドの引数で`int i`とか`String a`はNGです。意味の分かる名前にしましょう。`i`とか`a`はfor文の中などのみで利用するのが一般的です。
* sortToneUtilメソッドの引数で54を渡してる箇所がありますけど、これは意図的でしょうか？SORT_STRINGがそんなに長くないのでもし意図的だとしたらクラッシュするなぁと。実装途中ですか？
* `Arrays.asList(a.split(","));`を使ってるのはグッドです！
* **すいません、次から現状「やりたきこと」でどこまでは実装出来てるかお知らせしてもらえるとありがたいです。**

**Comment by w-tensyo** [comment]
- sortToneUtilメソッドとmakeArrayメソッドはわざわざメソッド化しなくてもいいかも。
　→　sortToneUtil,makeArrayメソッドのメソッド化をやめました。

- sortToneUtilメソッドの引数で54を渡してる箇所がありますけど、これは意図的でしょうか？SORT_STRINGがそんなに長くないのでもし意図的だとしたらクラッシュするなぁと。実装途中ですか？
 → 54で指定しているのは、あまり意思はないです・・・。指定箇所から最後までを選択したかっただけです。54の指定をなくしました！


- すいません、次から現状「やりたきこと」でどこまでは実装出来てるかお知らせしてもらえるとありがたいです。

以下に「やりたきこと」と「実装できていること」を記載します！


**1.ラジオボタンのチェック状態に合わせて、左側プルダウンに表示する配列を切り替える**
　　→　これはできている

**2.左側プルダウンで選択したものを、画面下部のリストビューに表示する**
　　→　一部実装できているものの、課題あり。
　　1で切り替えた内容が反映できていない。
　　76,79行目で変数itemに入れた定数を"SpinnerSelectedListener"内のswitch文でソート　→　その後、画面下部のリストビューに表示したいが、手段が思いついていない。

**3.画面下のリスストビューに、配列化した全てをリストで表示するのではなく、特定の番号（インデックス番号）のみを表示したい。**
　　→　完全未実装
　　これについては、最終的には右プルダウンで特定番号を指定できるようにしたい。
　　例えば、右プルダウンの1番上の選択肢を選択した時は、配列のインデックス番号0,3,5,6に該当するリストのみをリストビューに表示したい。

**4.3で表示しているリストビューに文字列を追加したい**
　　→　完全未実装
　　例）リストビュー一番上には　インデックス番号0の文字列 + "majar"
　　　　リストビュー二番目には　インデックス番号3の文字列 + "minar"
　　といった感じで、各リスト内に規則性のある文字列を付与する
　　これについても、3.同様、右プルダウンの選択肢ごとに規則性をもたせたい

**Comment by shinsuke-fujita** [comment]
> 76,79行目で変数itemに入れた定数を"SpinnerSelectedListener"内のswitch文でソート　→　その後、画面下部のリストビューに表示したいが、手段が思いついていない。

これですが、今動かすと左のプルダウンを選択すると連動してリストの内容が変わってますが、やりたい事は今の動作ではないのでしょうか？

あと気になったのですが、itemに対して左のradiobuttonの選択状態によりSORT_STRING_FLAT or SORT_STRING_SHARPを代入してます。同じ変数itemに対してspinnerを選んだ時はSORT_STRING_SHARP.substring()の結果を代入してます。
itemの用途ってどういう役割をイメージしてますか？

**Comment by shinsuke-fujita** [comment]
1.ラジオボタンのチェック状態に合わせて、左側プルダウンに表示する配列を切り替える
　　→　これはできている
     **_(追記)ラジオボタンの初期値がないので設定した方がいいかなと思います。
　     →onCreate()内でやるイメージ_**

2.左側プルダウンで選択したものを、画面下部のリストビューに表示する
　　→　一部実装できているものの、課題あり。
　　1で切り替えた内容が反映できていない。
　　　**_(追記)SpinnerSelectedListener内ではSORT_STRING_SHARPをsubstringしてるためラジオボタンの変更が反映されてません。せっかくleftToneSelect#setOnCheckedChangeListenerでitemの文字列を入れ替えてるので、SpinnerSelectedListenerではitemをsubstringして表示する文字列を生成すればいいのではないでしょうか？ただ今のようにitemを書き換えてしまうとダメだと思うので、switchの外でStringの変数を宣言し、その変数にitemをsubstringした物を入れて使えばいいかと。_**

3.画面下のリスストビューに、配列化した全てをリストで表示するのではなく、特定の番号（インデックス番号）のみを表示したい。
　　→　完全未実装
　　　**_(追記)まず右のスピナーの選択位置を取得する必要があります。（今は左スピナーの選択位置でswitchしてますよね？）
　　　　　　右スピナーをfindViewByIdで取得します。
　　　　　　SpinnerSelectedListenerで、
　　　　　　　・rightSpinnerのgetSelectedItemPosition()で位置を取得。
　　　　　　　・上記位置によってsubstringする場所を変更する
　　　　　　　・それを表示させる_**

4.3で表示しているリストビューに文字列を追加したい
　　→　完全未実装
　　例）リストビュー一番上には　インデックス番号0の文字列 + "majar"
　　　　リストビュー二番目には　インデックス番号3の文字列 + "minar"
　　　**_(追記)リストのポジション毎に付与する文字は決まってるんですよね？
　　　　　　それであれば、substringした結果をListに変換した後に、
　　　　　　　・新しいListを宣言しておく
　　　　　　　・substring結果のListでループ
　　　　　　　・ループのindexで付与する文字列を判断
　　　　　　　・新たな文字列を新しいListに付与
　　　　　　分かりづらそうなので、実装イメージも載せます↓_**
```
            List<String> newList = new ArrayList<>();
            for (int i = 0; i < toneList.size(); i++) {
                String toneString = toneList.get(i);
                // リストのポジション毎に特定の文字列を付与する
                if (i == 0) {
                    toneString = toneString.concat("majar");
                } else if (i == 1) {
                    toneString = toneString.concat("minar");
                } else if (i == 2) {
                    toneString = toneString.concat("hoge");
                }
                // 新しいリストに追加
                newList.add(toneString);
            }
```

> これについても、3.同様、右プルダウンの選択肢ごとに規則性をもたせたい 

これ付与する文字列を右プルダウンによって変化させたいってことですか？
もしそうならプルダウン毎に付与する文字を配列で持たせればいいかな。
例：右スピナーごとの付与する文字列定義。
```
      String[] majarAddString = {"AAA", "BBB", "CCC", "DDD"};
      String[] minarAddString = {"aaa", "bbb", "ccc", "ddd"};
      String[] melodyMinarAddString = {"111", "222", "333", "444"};
      String[] harmonyMinarAddString = {"123", "456", "789", "jif"};
```
この中からどれを使うかは右スピナーの選択位置によって決めて、上記for文の中で利用する
